---
# Source: scheduled-scaling-sandbox/templates/scaling.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaling-service-account
  namespace: cronjob-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaling-role
  namespace: cronjob-sandbox
rules:
- apiGroups: ["apps"] # API group for Deployments
  resources: 
  - "deployments"
  - "deployments/scale",
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaling-role-binding
  namespace: cronjob-sandbox
subjects:
- kind: ServiceAccount
  name: scaling-service-account
  namespace: cronjob-sandbox
roleRef:
  kind: Role
  name: scaling-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-deployment
  namespace: cronjob-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling
  template:
    metadata:
      labels:
        app: scaling
    spec:
      serviceAccountName: scaling-service-account
      containers:
      - name: scaler
        image: us-east1-docker.pkg.dev/dv01-prj-shared-art-reg-6j49/dv01-shared-art-reg-01/watching-scaler:v1
---
# Source: scheduled-scaling-sandbox/templates/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-name-from-values-file-deploy
  namespace: cronjob-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-container
        image: busybox
        command: ["sh", "-c", "while true; do echo hello; sleep 1; done"]
