---
# Source: scheduled-scaling-sandbox/templates/cronjobs.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-1
  namespace: cronjob-sandbox
spec:
  schedule: "* * * * *"
  timeZone: America/New_York
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo $CJ_NAME says $MESSAGE
            env:
            - name: MESSAGE
              value: "hello from job 1"
            - name: CJ_NAME
              value: "cronjob-1"
          restartPolicy: OnFailure
---
# Source: scheduled-scaling-sandbox/templates/cronjobs.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-2
  namespace: cronjob-sandbox
spec:
  schedule: "* * * * *"
  timeZone: America/New_York
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo $CJ_NAME says $MESSAGE
            env:
            - name: MESSAGE
              value: "hello from job 2"
            - name: CJ_NAME
              value: "cronjob-2"
          restartPolicy: OnFailure
