{{- $scheduledScaling := fromJson .Values.scheduledScaling }}
{{- range $scheduledScaling.schedules }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace}}
spec:
  schedule: "{{ .cron }}"
  timeZone: America/New_York
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo $CJ_NAME says $MESSAGE
            env:
            - name: MESSAGE
              value: "{{ .message }}"
            - name: CJ_NAME
              value: "{{ .name }}"
          restartPolicy: OnFailure
---
{{- end }}